---
- name: Varibles Demo
  hosts: g1
  become: yes
  vars :
  myusername: techt
  
  tasks:
    - name: Update  Dynamic Page
      template: 
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
        force: yes 
...