---
  - name: Update  Static Page
    copy: 
      src: static.html
      dest: /var/www/html/static.html
      force: yes 
        
  - name: Update  Static Page
    template: 
      src: dynamic.j2
      dest: /var/www/html/dynamic.html
      force: yes 
...